echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 
echo starting
python Data_preparation.py
sleep 300 

